### ISSUE TITLE
Dataset Requisition

### ISSUE THREAD

**Issue by zhongchenzhao** [liangjiubujiu/CTooth#2]
Hi, I wish to use CTooth dataset for academic research purposes. I have sent an email but have not received any response. If possible, can you send this dataset to my email (13193491346@sjtu.edu.cn)? Thanks!

**Comment by liangjiubujiu** [comment]
Hi Zhongchen, 
    Thanks for your email. We have been reviewing our data annotations these days.  We will release the dataset after the dataset paper is accepted by the springer publisher. Please kindly star ⭐ our repository and you will receive the dataset updates asap within about two months.

**Comment by zhongchenzhao** [comment]
Ok, thanks!

**Comment by zzmicer** [comment]
Hi @liangjiubujiu 
Thank you for your research, you've made an amazing work!
I am an independent researcher from Belarus. I sent an email 3 days ago, but didn't get any response. Could you please check it. Thanks!

**Comment by rachelwqsu** [comment]
Hi @liangjiubujiu
I am an international school student in China and I wish that I can get this CTooth dataset for my academic research. I had already sent the email to the address mentioned in the README file but I haven't received any reply yet. so is it possible for you to check it and send the dataset to my email(rachelsuwq@gmail.com)? Thanks a lot!

**Comment by liangjiubujiu** [comment]
> Hi @liangjiubujiu Thank you for your research, you've made an amazing work! I am an independent researcher from Belarus. I sent an email 3 days ago, but didn't get any response. Could you please check it. Thanks!

I have replied to all the emails. Hope you have received the dataset download link. Please don't hesitate to contact me if you have any questions!

**Comment by liangjiubujiu** [comment]
> Hi @liangjiubujiu I am an international school student in China and I wish that I can get this CTooth dataset for my academic research. I had already sent the email to the address mentioned in the README file but I haven't received any reply yet. so is it possible for you to check it and send the dataset to my email([rachelsuwq@gmail.com](mailto:rachelsuwq@gmail.com))? Thanks a lot!

If you do not receive a download link so far, please write to me via acw499@qmul.ac.uk! I will send a link to you asap.

**Comment by s191151371** [comment]
Hi @liangjiubujiu. I'm student from Malaysia. I had already sent the request email on 14 November via my email (s191151371@studentmail.unimap.edu.my) but I haven't received any reply yet. Can you check for my email, I worried that email not be sent to you. Thank you so much.

**Comment by liangjiubujiu** [comment]
> s191151371

Hi， thanks for your message.  Actually, I have not received your email via  [s191151371@studentmail.unimap.edu.my](mailto:s191151371@studentmail.unimap.edu.my). 

 Would it be possible to send me the application mail again via another educational mailbox?  The download link will be sent to you in a few days if you follow [these instructions](https://github.com/liangjiubujiu/CTooth/blob/main/Data_requistion.md) carefully.

**Comment by s191151371** [comment]
> 

Hi, I have sent the email again using the same email. Thank you so much.
